---
- name: VM Provisioning
  hosts: new_vms
  strategy: free
  
  roles:
    - repos # ok
    - utils # ok
    - docker # ok
    - ipsec-prereqs # ok
    - kubernetes/prepare_nodes # ok

  vars_files:
    - ../vars/main.yml